config/routes.rb
Rails.application.routes.draw do


 #顧客　トップページ
  root to: 'public/homes#top'
 #顧客　Aboutページ
  get 'about' => 'public/homes#about', as: 'about'
  
 #管理者　トップページ　注文履歴一覧
  get 'admin' => 'admin/homes#top'
  
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
   devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
 
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #管理者　注文詳細　商品　顧客管理
   
   namespace :admin do
    resources :items
    resources :customers
    resources :orders, only: [:show]
  end


  

  scope module: :public do
   
   #顧客情報
   get   'customers/my_page'          => 'customers#show', as: 'my_page'
   get   'customers/information/edit' => 'customers#edit'
   patch 'customers/information'      => 'customers#update'
   get   'customers/quit'             => 'customers#quit'
   patch 'customers/withdraw'         => 'customers#withdraw'

   
   #顧客　カート内商品消去
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
   
   #顧客　注文情報確認　完了
   post 'orders/confirm' => 'orders#confirm'
   get  'orders/thanx'   => 'orders#thanx'
   
    #顧客　商品　顧客管理　カート内商品　注文
   resources :items,      only: [:index, :show]
   resources :customers,  only: [:index, :show, :edit, :update]
   resources :cart_items, only: [:index,:update, :destroy, :create]
   resources :orders,     only: [:new, :create, :index, :show]
  
  end
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items, dependent: :destroy
  has_many :order_detail, dependent: :destroy
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  def add_tax_price
      (self.price * 1.10).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "You have updated user info successfully."
      redirect_to admin_item_path(@item.id)
    end
  end
  
  private 
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-10">
    <div class="row mt-4">
     <h2 class="offset-md-1">商品編集</h2>
    </div>
   
    <%= form_with model: @item, url: admin_item_path(@item.id), method: :PATCH do |f| %>
       <div class="row form-group mt-4">
        <%= f.label :image, '商品画像', class: "col-md-2 offset-md-2" %>
        <%= f.file_field :image, accept: "image/*", class: "col-md-4" %>
       </div>
       <div class="row form-group">
        <%= f.label :name, '商品名', class: "col-md-2 offset-md-2" %>
        <%= f.text_field :name, class: "col-md-4" %>
       </div>
       <div class="row form-group">
        <%= f.label :introduction, '商品説明', class: "col-md-2 offset-md-2" %>
        <%= f.text_area :introduction, size: "10x5", class: "col-md-4" %>
       </div>
       <div class="row form-group">
        <%= f.label :price, '税抜価格', class: "col-md-2 offset-md-2" %>
        <%= f.text_field :price, class: "col-md-4" %>円
       </div>
       <div class="row form-group mt-4">
         <%= f.submit '変更を保存', class: 'btn btn-success offset-md-5' %>
        </div>
    <% end %>
   </div>
 </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-9 mx-auto">
            <div class="row">
                <h2 class="col-md-9 offset-md-1">商品一覧</h2>
                <div class="col-md-1">
                <%= link_to new_admin_item_path do %>
                    <button class="btn btn-outline-dark">＋</button>
                <% end %>
                </div>
            </div>
            
            
            <table class="table">
                <thead class="bg-secondary text-light">
                    <tr>
                        <th>商品ID</th>
                        <th>商品名</th>
                        <th>税抜価格</th>
                    </tr>
                </thead>
                <tbody>
                  <% @items.each do |item| %>
                    <tr>
                        <td><%= item.id %></td>
                        <td>
                            <%= link_to admin_item_path(item.id), class: 'text-dark border-bottom border-dark' do %>
                            <%= item.name %>
                            <% end %>
                        </td>
                        <td><%= item.price.to_s(:delimited) %></td>
                    </tr>
                  <% end %>
                </tbody>
                 
                </table>
            <div class="d-flex justify-content-center mt-5">
                <%= paginate @items %>
            </div>
        </div>
    </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
    <div class="row mt-5">
        <div class="col-md-10">
                <h2>商品新規登録</h2>
                
                <%= form_with model: @item, url: admin_items_path do |f| %>
                    <div class="row form-group mt-5">
                        <%= f.label :image, '商品画像', class: "col-md-2 offset-md-1" %>
                        <%= f.file_field :image, class: "col-md-4", accept: "image/*" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :name, '商品名', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :name, placeholder: "商品名", class: "col-md-4" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :introduction, '商品説明', class: "col-md-2 offset-md-1" %>
                        <%= f.text_area :introduction, size: "10x5", placeholder: "ここに説明文を記述します", class: "col-md-4" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :price, '税抜価格', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :price, placeholder: "1000", class: "col-md-4" %>円
                    </div
                    <div class="row form-group">
                    <%= f.submit '新規登録', class: "btn btn-success col-md-2 offset-md-3" %>
                    </div>
                <% end %>
        </div>
    </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
    <div><%= flash[:success] %></div>
    <div class="row mt-4">
        <h2 class="offset-md-1">商品詳細</h2>
    </div>
    
    <div class="row mt-5">
        <div class="col-md-3">
            <%= image_tag @item.get_image(240,200) %>
        </div>
        
        <div class="col-md-6">
            <div class="row">
                <p class="col-md-3">商品名</p>
                <span class="col-md-6"><%= @item.name %></span>
            </div>
             <div class="row">
                <p class="col-md-3">商品説明</p>
                <span class="col-md-6"><%= @item.introduction %></span>
            </div>
             <div class="row mt-2">
                <p class="col-md-3">税込価格<br>(税抜価格)</p>
                <span class="col-md-6"><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</span>
            </div>
            <div class="row">
                 <%= link_to '編集する', edit_admin_item_path, class: 'btn btn-success btn-lg col-md-3 offset-md-2 mt-3' %>
            </div>
        </div>
    </div>
       
    
</div>