config/routes.rb
Rails.application.routes.draw do


 #顧客　トップページ
  root to: 'public/homes#top'
 #顧客　Aboutページ
  get 'about' => 'public/homes#about', as: 'about'
  
 #管理者　トップページ　注文履歴一覧
  get 'admin' => 'admin/homes#top'
  
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
   devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
 
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #管理者　注文詳細　商品　顧客管理
   
   namespace :admin do
    resources :items
    resources :customers
    resources :orders, only: [:show]
  end


  

  scope module: :public do
   
   #顧客情報
   get   'customers/my_page'          => 'customers#show', as: 'my_page'
   get   'customers/information/edit' => 'customers#edit'
   patch 'customers/information'      => 'customers#update'
   get   'customers/quit'             => 'customers#quit'
   patch 'customers/withdraw'         => 'customers#withdraw'

   
   #顧客　カート内商品消去
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
   
   #顧客　注文情報確認　完了
   post 'orders/confirm' => 'orders#confirm'
   get  'orders/thanx'   => 'orders#thanx'
   
    #顧客　商品　顧客管理　カート内商品　注文
   resources :items,      only: [:index, :show]
   resources :customers,  only: [:index, :show, :edit, :update]
   resources :cart_items, only: [:index,:update, :destroy, :create]
   resources :orders,     only: [:new, :create, :index, :show]
  
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
    flash[:success] = "You have updated user info successfully."
    redirect_to admin_customer_path(@customer.id)
    end
  end
  
   private 
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana,
                                        :postal_code, :address, :telephone_number, :email)
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-11">
            <div class="row mt-4">
                <h2 class="col-md-7"><%= (@customer.first_name + @customer.last_name) %>さんの会員情報編集</h2>
            </div>
            
            <div>
                <%= form_with(model: @customer, url: admin_customer_path, method: :PATCH) do |f| %>
                    <div class="row form-group mt-4">
                        <%= f.label :id, '会員ID', class: "col-md-2 offset-md-1" %> 
                        <%= f.label :"#{@customer.id}", class: "col-md-4" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :name, '氏名', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :first_name, class: "col-md-2" %>
                        <%= f.text_field :last_name, class: "col-md-2 ml-3" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :kana, 'フリガナ', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :first_name_kana, class: "col-md-2" %>
                        <%= f.text_field :last_name_kana, class: "col-md-2 ml-3" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :postal_code, '郵便番号', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :postal_code, class: "col-md-2" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :address, '住所', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :address, class: "col-md-6" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :telephone_number, '電話番号', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :telephone_number, class: "col-md-2" %>
                    </div>
                    <div class="row form-group">
                        <%= f.label :email, 'メールアドレス', class: "col-md-2 offset-md-1" %>
                        <%= f.text_field :email, class: "col-md-2" %>
                    </div>
                    <div class="row mt-4">
                        <%= f.submit '変更を保存', class: 'btn btn-success col-md-2 offset-md-3' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-7 mx-auto">
        <div class="col-md-9">
            <div class="row">
                <h2 class="offset-md-1">会員一覧</h2>
            </div>
        </div>
            <table class="table">
                <thead class="bg-secondary text-light">
                    <tr>
                        <th>会員ID</th>
                        <th>氏名</th>
                        <th>メールアドレス</th>
                        <th>ステータス</th>
                    </tr>
                </thead>
                <tbody>
                    <% @customers.each do |customer| %>
                    <tr>
                        <td><%= customer.id %></td>
                        <td>
                            <%= link_to admin_customer_path(customer.id), class: "text-dark border-bottom border-dark" do %>
                                <%= (customer.first_name+customer.last_name) %>
                            <% end %>
                        </td>
                        <td><%= customer.email %></td>
                        <td>
                            <% if customer.is_deleted == false %>
                            <span class="text-success">有効</span>
                            <% else %>
                            <span class="text-secondary">退会</span>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="d-flex justify-content-center mt-5">
                <%= paginate @customers %>
            </div>
      </div>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-11">
            <%= flash[:success] %>

            <div class="row">
                <h2 class="col-md-5"><%= (@customer.first_name+@customer.last_name) %>さんの会員詳細</h2>
            </div>

            <div class="row mt-4">
                <p class="col-md-2">会員ID</p>
                <span class="col-md-6"><%= @customer.id %></span>
            </div>
            <div class="row">
                <p class="col-md-2">氏名</p>
                <span class="col-md-6"><%= (@customer.first_name+@customer.last_name) %></span>
            </div>
            <div class="row">
                <p class="col-md-2">フリガナ</p>
                <span class="col-md-6"><%= (@customer.first_name_kana+@customer.last_name_kana) %></span>
            </div>
                
            <div class="row">
                <p class="col-md-2">郵便場号</p>
                <span class="col-md-6"><%= @customer.postal_code %></span>
            </div>
            <div class="row">
                <p class="col-md-2">住所</p>
                <span class="col-md-6"><%= @customer.address %></span>
            </div>
            <div class="row">
                <p class="col-md-2">電話番号</p>
                <span class="col-md-6"><%= @customer.telephone_number %></span>
            </div>
            <div class="row">
                <p class="col-md-2">メールアドレス</p>
                <span class="col-md-6"><%= @customer.email %></span>
            </div>
            <div class="row">
                <%= link_to '編集する', edit_admin_customer_path, class: 'btn btn-success col-md-2 offset-md-2 mt-2' %>
            </div>
        </div>
    </div>
</div>