config/routes.rb
Rails.application.routes.draw do


 #顧客　トップページ
  root to: 'public/homes#top'
 #顧客　Aboutページ
  get 'about' => 'public/homes#about', as: 'about'
  
 #管理者　トップページ　注文履歴一覧
  get 'admin' => 'admin/homes#top'
  
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
   devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
 
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #管理者　注文詳細　商品　顧客管理
   
   namespace :admin do
    resources :items
    resources :customers
    resources :orders, only: [:show]
  end


  

  scope module: :public do
   
   #顧客情報
   get   'customers/my_page'          => 'customers#show', as: 'my_page'
   get   'customers/information/edit' => 'customers#edit'
   patch 'customers/information'      => 'customers#update'
   get   'customers/quit'             => 'customers#quit'
   patch 'customers/withdraw'         => 'customers#withdraw'

   
   #顧客　カート内商品消去
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
   
   #顧客　注文情報確認　完了
   post 'orders/confirm' => 'orders#confirm'
   get  'orders/thanx'   => 'orders#thanx'
   
    #顧客　商品　顧客管理　カート内商品　注文
   resources :items,      only: [:index, :show]
   resources :customers,  only: [:index, :show, :edit, :update]
   resources :cart_items, only: [:index,:update, :destroy, :create]
   resources :orders,     only: [:new, :create, :index, :show]
  
  end
  
  
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    has_many :items
    
    
    validates :destination, presence: true
    validates :postal_code, presence: true
    validates :address_name, presence: true
   
    enum payment_method: { credit_card: 0, transfer: 1 }
    
    def subtotal
        item.add_tax_price * amount
    end
    
    def add_tax_price
      (self.price * 1.10).floor
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
    <div class="row">
         <div class="col-md-11">
            <div class="row mt-4">
                <h2><strong>注文履歴詳細</strong></h2>
            </div>
        
            <div class="row mt-4">
                    <h5 class="col-md-2"><strong>購入者</strong></h5>
                    <%= link_to admin_customer_path(@order.customer_id), class: "text-dark col-md-3" do %>
                    <%= (@order.customer.first_name + @order.customer.last_name) %>
                    <% end %>
            </div>
            <div class="row mt-1">
                    <h5 class="col-md-2"><strong>注文日</strong></h5>
                    <span class="col-md-3"><%= @order.created_at.strftime('%Y/%m/%d') %></span>
            </div>
            <div class="row mt-1">
                    <h5 class="col-md-2"><strong>配送先</strong></h5>
                    <span class="col-md-5">
                    〒<%= @order.postal_code %>
                    <%= @order.destination %><br>
                    <%= @order.address_name %>
                    </span>
            </div>
            <div class="row mt-1">
                    <h5 class="col-md-2"><strong>支払方法</strong></h3>
                    <span class="col-md-3">
                        <%= @order.payment_method_i18n %>
                    </span>
            </div>
            
            <div class="row mt-4">
                <div class="col-md-8">
                    <table class="table">
                        <thead class="bg-secondary text-light">
                            <th>商品名</th>
                            <th>単価（税込）</th>
                            <th>数量</th>
                            <th>小計</th>
                        </thead>
                        <tbody>
                            <% @order_details.each do |order_detail| %>
                            <tr>
                                <td>
                                    <%= order_detail.item.name %>
                                </td>
                                <td>
                                    <%= (order_detail.price * 1.1).floor.to_s(:delimited) %>
                                </td>
                                <td>
                                    <%= order_detail.amount %>
                                </td>
                                <td>
                                    <%= (order_detail.price * order_detail.amount * 1.1).floor.to_s(:delimited) %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-3 d-flex justify-content-end flex-column ml-4">
                    <div class="row">
                        <h5><strong>商品合計</strong></h5>
                        <%= (@order.amount_billed - @order.postage).to_s(:delimited) %>円
                    </div>
                    <div class="row">
                        <h5><strong>送料</strong></h5>
                        <%= @order.postage %>円
                    </div>
                    <div class="row">
                        <h5><strong>請求金額合計</strong></h5>
                        <%= @order.amount_billed.to_s(:delimited) %>円
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>