config/routes.rb
Rails.application.routes.draw do


 #顧客　トップページ
  root to: 'public/homes#top'
 #顧客　Aboutページ
  get 'about' => 'public/homes#about', as: 'about'
  
 #管理者　トップページ　注文履歴一覧
  get 'admin' => 'admin/homes#top'
  
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
   devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
 
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #管理者　注文詳細　商品　顧客管理
   
   namespace :admin do
    resources :items
    resources :customers
    resources :orders, only: [:show]
  end


  

  scope module: :public do
   
   #顧客情報
   get   'customers/my_page'          => 'customers#show', as: 'my_page'
   get   'customers/information/edit' => 'customers#edit'
   patch 'customers/information'      => 'customers#update'
   get   'customers/quit'             => 'customers#quit'
   patch 'customers/withdraw'         => 'customers#withdraw'

   
   #顧客　カート内商品消去
   delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
   
   #顧客　注文情報確認　完了
   post 'orders/confirm' => 'orders#confirm'
   get  'orders/thanx'   => 'orders#thanx'
   
    #顧客　商品　顧客管理　カート内商品　注文
   resources :items,      only: [:index, :show]
   resources :customers,  only: [:index, :show, :edit, :update]
   resources :cart_items, only: [:index,:update, :destroy, :create]
   resources :orders,     only: [:new, :create, :index, :show]
  
  end
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのcake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom border-dark">
        <nav class="navbar navbar-expand-lg navbar-light">
         <div class="container">
            <div class="navbar-brand">
              <% if admin_signed_in? %>
                <%= link_to admin_path, class: "text-dark" do %>
                  <h1 class="border border-dark py-2 px-5">ながのcake</h1>
                <% end %>
              <% elsif customer_signed_in? %>
                <%= link_to root_path, class: "text-dark" do %>
                <h1 class="border border-dark py-2 px-5">ながのcake</h1>
                <% end %>
              <% else %>
                <%= link_to root_path, class: "text-dark" do %>
                <h1 class="border border-dark py-2 px-5">ながのcake</h1>
                <% end %>
              <% end %>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if customer_signed_in? %>
                  <li class="customer-name style">
                    ようこそ、<%= current_customer.first_name %>さん！
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4">
                    <%= link_to "マイページ", my_page_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
                  </li>
                <% elsif admin_signed_in? %>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "商品一覧", admin_items_path, class: "nav-link text-dark" %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4  ">
                    <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-dark" %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "注文履歴一覧", admin_path, class: "nav-link text-dark" %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                  </li>
                <% else %>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "About", about_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 "> 
                    <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item btn btn-outline-secondary ml-4 ">
                    <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
                  </li>
                <% end %>
              </ul>
            </div>
        </div><!--container--->
      </nav>
    </header>
    <main style="height: 90vh;" class="my-5">
    <%= yield %>
    </main>
    <footer style="height: 60px;" class="flexed-bottom mx-0  border-top border-dark">
      
    </footer>
  </body>
</html>